# Configuration file version
apiVersion: 1

datasources:

  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: hostapp
    user: postgres
    secureJsonData:
      password: 'changeme'
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: true
      timeInterval: "1s"